# CraftAttack Plugin Config file

# Worldboarder at the Beginnint of the event
worldborder:
  initial: 100.0
  target: 20000.0
  center:
    x: 0.0
    z: 0.0

# Welcome-Texts
title: '{"text":"Willkommen auf CraftAttack!","color":"red"}'
welcome: "&aWillkommen auf CraftAttack! Viel Spaß beim Spiel!"

# /craftattack teleportall and start teleport coordinates
teleport:
  x: 100.0
  y: 64.0
  z: 100.0

# The text under the tablist
tabtext: true
tab: '{"text":"Default Tab","color":"gold"}'

# Invsee-Feature activated or deactivated
invsee: true

#Spawn Elytra Configuration
SpawnElytra:
  enabled: false
  multiplyValue: 3
  boostEnabled: true
  world: world
  message: 'Boost ready: Press %key% to boost!'

# Spawn-Rage define
spawnArea:
  x1: 0
  y1: 0
  z1: 0
  x2: 0
  y2: 0
  z2: 0

# Status-definition
statuses:
  example1: '{"text":"example1", "color":"green", "bold":true}'
  example2: '{"text":"example2", "color":"red"}'

# Webservices
server:
  port: 8020
enable_webserver: false
enable_api: false

# Spawn-Teleporter
SpawnTeleporter:
  enabled: false
  region:
    world: "world"
    x1: 100
    y1: 64
    z1: 100
    x2: 130
    y2: 80
    z2: 130
  delay: 3
  teleport:
    world: "world"
    x: 200
    y: 70
    z: 200
  sound: "ENTITY_ENDERMAN_TELEPORT"

# Automaticly changing MOTD (this overwrites the MOTD in sht server.properties)
# Maintenance is the MOTD displayed in maintenance mode
motd:
  maintenance: "\u00a7c\u00a7lWartungsarbeiten!\u00a7r\n\u00a7c\u00a7oBitte versuche es in wenigen Minuten erneut!"
  interval: 2          # Intervall in Sekunden
  messages:
    - "\u00a7aCraftAttack13 \u00a76Community\u00a7r\n\u00a74Shopping-District\u00a7f Er\u00f6ffnung!"
    - "\u00a7aCraftAttack13 \u00a76Community\u00a7r\n\u00a7bOffizieller Start!"
