# CraftAttack Plugin Config file

# Worldborder beim Start
worldborder:
  initial: 100.0
  target: 20000.0
  center:
    x: 0.0
    z: 0.0

# Willkommenstexte
title: '{"text":"Willkommen auf CraftAttack!","color":"red"}'
welcome: "&aWillkommen auf CraftAttack! Viel Spaß beim Spiel!"

# /craftattack teleportall und Start Teleport Koordinaten
teleport:
  x: 100.0
  y: 64.0
  z: 100.0

# Text unter der Spielerliste, wenn TAB gedrückt wird
tabtext: true
tab: '{"text":"Default Tab","color":"gold"}'

# Invsee-Feature aktivieren oder deaktivieren
invsee: true

#Spawn Elytra Configuration
SpawnElytra:
  enabled: true
  multiplyValue: 3
  boostEnabled: true
  world: world
  message: 'Boost ready: Press %key% to boost!'

# Spawn Bereich Koordinaten
spawnArea:
  x1: 0
  y1: 0
  z1: 0
  x2: 0
  y2: 0
  z2: 0

# Statusdefinitionen
statuses:
  example1: '{"text":"example1", "color":"green", "bold":true}'
  example2: '{"text":"example2", "color":"red"}'