name: CraftAttack
version: "2.0.1"
main: de.vmoon.craftAttack.CraftAttack
api-version: "1.21"
authors: [ "VoidableMoon884" ]
description: "A CraftAttack Community Plugin"
website: "vmoon.de"

commands:
  craftattack:
    description: "Main CraftAttack command"
    usage: /craftattack <Unterbefehl>
    permission-message: "You don't have the permission to use this command!"
    aliases:
      - ca
  pvp:
    description: "Activates/Deactivates the pvp on the server"
    usage: /pvp <on|off>
    permission-message: "You don't have the permission to use this command!"
  status:
    description: "Shows the configured status"
    usage: /status <statusname>

permissions:
  ca.admin.start:
    description: "Erlaubt das Starten des CraftAttack-Events."
    default: op
  ca.admin.stop:
    description: "Erlaubt das Stoppen des laufenden CraftAttack-Events."
    default: op
  ca.admin.teleportall:
    description: "Erlaubt das Teleportieren aller Spieler zu den festgelegten Koordinaten."
    default: op
  ca.admin.settitle:
    description: "Erlaubt das Setzen des Titles via /craftattack settitle."
    default: op
  ca.admin.settab:
    description: "Erlaubt das Setzen des Tab-Texts via /craftattack settab."
    default: op
  ca.admin.spawn:
    description: "Erlaubt das Setzen des Spawn-Punkts und Bereichs"
    default: op
  ca.admin.reload:
    description: "Erlaubt das Neuladen der Config via /craftattack reload."
    default: op
  ca.admin.invsee:
    description: "Erlaubt das Sehen (und Bearbeiten) von Inventaren via /craftattack invsee."
    default: op
  ca.admin.pvp:
    description: "Erlaubt das Ein- und Ausschalten des PvP-Modus."
    default: op
  ca.admin.pregen:
    description: "Pregenerieren von Cunks"
    default: op
  ca.admin.maintenance:
    description: "Erlaubt das Verwalten des Wartungsmodus (start, stop, addplayer, removeplayer)."
    default: op
  ca.admin.tempban:
    description: "Erlaubt das temporäre Bannen von Spielern"
    default: op
  ca.admin.timeout:
    description: "Spieler timeouten"
    default: op
  ca.admin.join.always:
    description: "Man kann immer dem Server beitreten, auch wenn er voll ist"
    default: op
  ca.builder.spawn:
    description: "Erlaubt das Bauen im gesetzten Spawn-Bereich."
    default: false
  ca.user.status:
    description: "/status für die Benutzer"
    default: true